name: CI Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Force Reinstall Dependencies
        run: |
          # Upgrade base tools
          python -m pip install --upgrade pip setuptools wheel

          # Uninstall problematic packages
          pip uninstall -y numpy pandas pluggy || true
          pip uninstall -y numpy pandas pluggy || true
          pip uninstall -y numpy pandas pluggy || true

          # Force install exact versions
          pip install --no-cache-dir numpy==1.24.3
          pip install --no-cache-dir pandas==1.5.3
          pip install --no-cache-dir pluggy==1.5.0

          # Install other requirements
          pip install --no-cache-dir -r requirements.txt

          # Confirm versions
          python -c "import numpy; print('NumPy version:', numpy.__version__)"
          python -c "import pandas; print('Pandas version:', pandas.__version__)"
          python -c "import pluggy; print('Pluggy version:', pluggy.__version__)"

      - name: Run Unit Tests with Coverage
        run: |
          pytest --cov=app tests/

      - name: Check Code Coverage
        run: |
          coverage report --fail-under=80

      - name: Run Linting with Ruff
        run: |
          ruff .

      - name: Check Code Formatting with Black
        run: |
          black --check .
