name: CI Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies with Constraints
        run: |
          # Upgrade base tools
          python -m pip install --upgrade pip setuptools wheel

          # Uninstall existing numpy/pandas if present
          pip uninstall -y numpy pandas || true

          # Install exactly what you want
          pip install --no-cache-dir --no-deps "numpy==1.26.4" "pandas==1.5.3"

          # Install the rest using constraints to enforce numpy==1.26.4
          pip install --no-cache-dir -r requirements.txt -c constraints.txt

      - name: Run Unit Tests with Coverage
        run: |
          pytest --cov=app tests/

      - name: Check Code Coverage
        run: |
          coverage report --fail-under=80

      - name: Run Linting with Ruff
        run: |
          ruff .

      - name: Check Code Formatting with Black
        run: |
          black --check .
