name: CI Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Force Downgrade NumPy to 1.24.3 and install dependencies
        run: |
          # Upgrade pip, setuptools, wheel
          python -m pip install --upgrade pip setuptools wheel
          
          # Uninstall any existing numpy and pandas to ensure a clean state
          pip uninstall -y numpy pandas || true
          
          # Force install the exact versions you need
          pip install --no-cache-dir --ignore-installed "numpy==1.24.3" "pandas==1.5.3"
          
          # Install all requirements (make sure your requirements.txt is updated)
          pip install --no-cache-dir -r requirements.txt

          # Install additional tools like ruff and black if not in requirements.txt
          pip install ruff black

          # Confirm installed versions (optional)
          python -c "import numpy; print('NumPy version:', numpy.__version__)"
          python -c "import pandas; print('Pandas version:', pandas.__version__)"
          python -c "import ruff; print('Ruff version:', ruff.__version__)" || echo "Ruff not installed"

      - name: Run Unit Tests with Coverage
        run: |
          pytest --cov=app tests/

      - name: Check Code Coverage
        run: |
          coverage report --fail-under=80

      - name: Run Linting with Ruff
        run: |
          ruff check . --fix
          ruff check . --exit-zero

      - name: Check Code Formatting with Black
        run: |
          black .
          black --check .
          black . --exclude '/\.gitignore$'

